volumes:
  ntfy-data:
    external: true
  ntfy-cache:
    external: true

configs:
  ntfy-server-config:
    external: true

networks:
  traefik-internetwork:
    external: true

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    command:
      - serve
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - NTFY_UPSTREAM_ACCESS_TOKEN=${NTFY_ACCESS_TOKEN}
      - NTFY_BASE_URL=https://${BASE_URL}
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-data:/etc/ntfy
    configs:
      - source: ntfy-server-config
        target: /etc/ntfy/server.yml
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        max_failure_ratio: 0.5
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.125"  
          memory: "128M"
      labels:
        # Label for Shepherd service for autoupdate
        - "shepherd.enable=true"
        - "service.autodeploy=true"
        # Frontend
        - "traefik.enable=true"
        - "traefik.http.routers.ntfy.rule=Host(`${BASE_URL}`)"
        - "traefik.http.routers.ntfy.entrypoints=websecure"
        - "traefik.http.routers.ntfy.tls.certresolver=letsencrypt"
        - "traefik.http.services.ntfy.loadbalancer.server.port=80"
          
    networks:
      - traefik-internetwork
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
