services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    container_name: arcane-agent
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "100.116.205.94:3553:3553"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/arcane-data:/app/data
      - /mnt/docker-data/arcane/projects:/app/data/projects
      - /mnt/docker-data/arcane/templates:/app/data/templates
    mem_limit: 2G
    mem_reservation: 1G
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
    networks:
      - proxy

networks:
  proxy:
    external: true
