services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    container_name: arcane-agent
    restart: unless-stopped
    environment:
      - AGENT_MODE=true
      - EDGE_TRANSPORT=poll
      - AGENT_TOKEN=arc_d10997db84ee16ee07bb9480ebbbad53886bf9e4ef51dd402b00d133b1892d7a
      - MANAGER_API_URL=https://dashboard.mcb-homelab.com
      - LOG_LEVEL=debug
    ports:
      - "3553:3553"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/arcane-data:/app/data
      - /mnt/docker-data/arcane/projects:/app/data/projects
      - /mnt/docker-data/arcane/templates:/app/data/templates
    mem_limit: 1G
    mem_reservation: 1G
