services:
  cicd-testing:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        # Frontend
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`${ROOT_DOMAIN}`) && PathPrefix(`/cicd`)"
        - "traefik.http.routers.prometheus.entrypoints=websecure"
        - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
        - "traefik.http.services.prometheus.loadbalancer.server.port=80"
    networks:
      - traefik-internetwork

networks:
  traefik-internetwork:
    external: true

configs:
  proxy_config_prd:
    external: true
