apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-s3-secret-eso
  namespace: longhorn-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-secret-eso
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: minio-s3-secret
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: minio-s3-secret
        property: AWS_ENDPOINTS
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: minio-s3-secret
        property: AWS_SECRET_ACCESS_KEY
