apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production-external-app-cert
  namespace: production-external-apps
spec:
  secretName: production-external-app-cert-tls  # This is the TLS secret used in Ingress
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  commonName: "*.mcb-svc.work"
  dnsNames:
  - "*.mcb-svc.work"
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
