apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: production-external-apps
spec:
  type: ClusterIP
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
  selector: {}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: production-external-apps
subsets:
  - addresses:
      - ip: 192.168.1.6
    ports:
      - port: 8006
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: proxmox-headers
  namespace: production-external-apps
spec:
  headers:
    stsSeconds: 31536000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: proxmox-insecure
  namespace: production-external-apps
spec:
  insecureSkipVerify: true


