namespace: "cert-manager"
crds:
  enabled: true
extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53

nodeSelector:
  beta.kubernetes.io/arch: "arm64"
tolerations:
- key: "CriticalAddonsOnly"
  value: "true"
  operator: "Equal"
  effect: "NoExecute"
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"
