rancherImageTag: v2.11.1
ingress:
  enabled: true
  tls:
    source: letsEncrypt

hostname: rancher.mcb-svc.work

letEncrypt:
  environment: production
  email: JohnasHuy21091996@gmail.com
  ingress:
    class: traefik

replicas: 3
antiAffinity: preferred
topologyKey: kubernetes.io/hostname

extraTolerations:
- key: "CriticalAddonsOnly"
  value: "true"
  effect: "NoExecute"
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"

extraNodeSelectorTerms:
  - key: "node.cert-manager"
    operator: In
    values:
      - "true"
