additionalArguments:
  - "--entrypoints.portainer-agent.address=:9001"
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"

hostNetwork: true

ports:
  traefik:
    expose: 
      default: true
    port: 8083
    protocol: TCP
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
    port: 9080
  websecure:
    port: 9443
  portainer-agent:
    expose: 
      default: true
    port: 9001
    protocol: TCP

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

tolerations:
- key: "CriticalAddonsOnly"
  value: "true"
  effect: "NoExecute"
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"
