services:
  pgbouncer:
    image: edoburu/pgbouncer:${PGBOUNCER_IMAGE_TAG:-latest}
    container_name: pgbouncer
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
    hostname: pgbouncer
    env_file:
      - .env
    ports:
      - "100.116.205.94:5432:5432"
    volumes:
      - ${MASTER_DIR}/pgbouncer:/etc/pgbouncer
    restart: unless-stopped
    networks:
      db-intranet: {}
    mem_limit: 256M
    mem_reservation: 256m
    cpus: 1
    
networks:
  db-intranet:
    external: true