services:
  hbbs:
    container_name: rustdesk-hbbs
    mem_limit: 256M
    mem_reservation: 128M
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    env_file:
      - .env
    volumes:
      - ${MASTER_DIR}/rustdesk:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: rustdesk-hbbr
    mem_limit: 256M
    mem_reservation: 128M
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "3"
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    env_file:
      - .env
    volumes:
      - ${MASTER_DIR}/rustdesk:/root
    network_mode: "host"
    restart: unless-stopped