services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:${IMAGE_VERSION}
    container_name: dragonflydb-internal
    hostname: cache
    env_file:
      - .env
    ulimits:
      memlock: -1
    networks:
      proxy:
    restart: always
    volumes:
      - dragonflydb-data:/data
    mem_limit: 1G
    mem_reservation: 1G
    cpus: 2
      
networks:
  proxy:
    external: true
    
volumes:
  dragonflydb-data:
    external: true