apiVersion: v1
kind: Namespace
metadata:
  name: testing-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: testing-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: testing-deployment
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.1.30  # Set this to an available IP from your MetalLB pool
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
