services:
  ntfy-alert-bridge:
    image: docker.io/mcbourdeux/my-repo:ntfy-bridge-alert
    networks:
      - traefik-internetwork
    environment:
      - NTFY_TOPIC=${NTFY_TOPIC}
      - NTFY_URL=${NTFY_URL}
      - NTFY_USER=${NTFY_USER}
      - NTFY_PASS=${NTFY_PASS}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
      
  alertmanager:
    image: prom/alertmanager:latest
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--cluster.listen-address=0.0.0.0:9094'
      - '--cluster.peer=alertmanager:9094'
      - '--cluster.gossip-interval=200ms'
      - '--cluster.pushpull-interval=1m'
      - '--web.external-url=http://alertmanager:9093'
    networks:
      - traefik-internetwork
    ports:
      - published: 9093
        target: 9093
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
    volumes:
      - alertmanager_config:/etc/alertmanager
      - alertmanager_data:/alertmanager
    configs:
      - source: alertmanager-conf
        target: /etc/alertmanager/alertmanager.yml

configs:
  alertmanager-conf:
    external: true

volumes:
  alertmanager_config:
    driver: local
    # Mount the volume to the SeaweedFS mount point
    driver_opts:
      type: none
      device: /mnt/seaweedfs/mount/alertmanager/config
      o: bind
  alertmanager_data:
    driver: local
    # Mount the volume to the SeaweedFS mount point
    driver_opts:
      type: none
      device: /mnt/seaweedfs/mount/alertmanager/data
      o: bind

networks:
  traefik-internetwork:
    external: true
