services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - monitoring-internetwork
    deploy:
      placement:
        constraints: [node.role == manager]

  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    configs:
      - source: fluent-bit-config
        target: /fluent-bit/etc/fluent-bit.conf
      - source: fluent-bit-parser
        target: /fluent-bit/etc/parsers.conf
    networks:
      - monitoring-internetwork
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  elasticsearch_data:
    driver: local
  grafana_data:
    driver: local

networks:
  monitoring-internetwork:
    external: true

configs:
  fluent-bit-config:
    file: ./fluent-bit.conf
  fluent-bit-parser:
    file: ./parsers.conf