apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault.mcb-svc.work
      path: kubernetes
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-k3s-oracle
          role: eso-role
          serviceAccountRef:
            name: vault-auth
            namespace: default
