services:
  immich-cli:
    image: ghcr.io/immich-app/immich-cli:latest
    container_name: immich-cli-import-johnashuy21091996
    volumes:
        - /mnt/user/backups/temp-icloud-backup:/import:ro
    environment:
        - IMMICH_INSTANCE_URL=${IMMICH_INSTANCE_URL}
        - IMMICH_API_KEY=${IMMICH_API_KEY1}
    mem_limit: 256m
    mem_reservation: 256m
    command: upload --recursive --album /import
    
  immich-cli-2:
    image: ghcr.io/immich-app/immich-cli:latest
    container_name: immich-cli-import-thuynguyen220991
    volumes:
        - /mnt/user/backups/temp-icloud-backup2:/import:ro
    environment:
        - IMMICH_INSTANCE_URL=${IMMICH_INSTANCE_URL}
        - IMMICH_API_KEY=${IMMICH_API_KEY2}
    mem_limit: 256m
    mem_reservation: 256m
    command: upload --recursive --album /import